#!/bin/bash
\cp -f /usr/share/bleuzen-manjaro-kde-setup/* ~/.config/

# To apply changes, the user has to re-login -> Do logout
# Logout with confirmation:
qdbus org.kde.ksmserver /KSMServer logout 1 3 3
# Logout without confirmation:
#qdbus org.kde.ksmserver /KSMServer logout 0 3 3
