#!/bin/bash

if [ -z "$1" ]
then
    echo "Please pass the name as an argument for this command."
    echo "Example:"
    echo "$0 music"
    exit 1
fi

SINK_NAME="$1"

SINK_ID=$(pactl load-module module-remap-sink sink_name="$SINK_NAME" sink_properties=device.description="$SINK_NAME" remix=no)

# Optional: to set the master sink and number of channels:
#pactl load-module module-remap-sink sink_name="$SINK_NAME" sink_properties=device.description="$SINK_NAME" master=alsa_output.pci-0000_00_1f.3.analog-stereo channels=2 remix=no

echo "To unload this sink, type:"
echo "pactl unload-module $SINK_ID"
