#!/bin/bash

if [ -z "$1" ]
then
    echo "Please pass the name as an argument for this command."
    echo "Example:"
    echo "$0 music"
    exit 1
fi

SINK_NAME="$1"

pactl load-module module-null-sink sink_name="$SINK_NAME" sink_properties=device.description="$SINK_NAME"
