#!/bin/bash
if [[ $EUID -ne 0 ]];
then
    exec sudo /bin/bash "$0" "$@"
fi

if [ -z "$1" ]
then
    echo "Please pass the new size (or 'disable') as an argument for this command."
    echo "Example:"
    echo "$0 6G"
    exit 1
fi

NEW_SIZE="$1"
SWAPFILE="/swapfile"
FSTAB_LINE="$SWAPFILE none swap defaults 0 0"

if [ -f "$SWAPFILE" ]
then
    swapoff $SWAPFILE
    rm $SWAPFILE
    echo "Deleted old swap file"
fi

if [ $NEW_SIZE = "disable" ]
then
    # Only create an empty dummy file and exit
    echo "" > $SWAPFILE
    echo "Swap file disabled"

    # Remove fstab entry
    sed -i.bak "\@^$FSTAB_LINE@d" /etc/fstab

    # Display warning message
    echo "WARNING: This also removed the /etc/fstab entry for the swapfile. Currently re-creating it is not supported. You have to add the entry manually if you want to enable the swapfile again."

    # Exit since we are done at this point
    exit 0
fi

echo "(Re)creating swap file ..."
fallocate -l $NEW_SIZE $SWAPFILE
chmod 600 $SWAPFILE
mkswap $SWAPFILE
swapon $SWAPFILE
#echo $FSTAB_LINE >> /etc/fstab
